### PR TITLE
Added cookie injection support for the existing rule for asus.com

### LINKED ISSUE #336: Cookie injection support could be added to the existing rule for asus.com
Currently, the existing cookie banner handling rule for asus.com only supports button clicking, and it works just fine. However, asus.com is a relatively highly visited website and seems to be a good candidate to also add cookie injection support for it.

The cookies in question that should do the trick:
Consent-cookies-used-by-asus-com

### PR DESCRIPTION
**Pull request by Greg-21**
In this pull request, I added cookie injection support for the rule that already exists for asus.com.

Resolves #336

### CODE REVIEW

**Review by abhishekmadan30 — CHANGES_REQUESTED** [review]
I tested the cookie rule you have provided and I can't get it to work. You test only using the cookie injector mechanism by setting `cookiebanners.bannerClicking.enabled` to false. Let me know if it still works on your end and I can take another look at it

**Comment by Greg-21** [comment]
I've just tested the rule with `cookiebanners.bannerClicking.enabled` set to `false`, and everything seems to be working fine on my end. Here's a screenshot as proof:
Injected-cookies-and-no-banner

**Comment by abhishekmadan30** [comment]
Hi, I still can't get the cookie injection to work as whenever the cookies get injected, I find there values get reset. Since there is already a working click rule, I think this issue can be closed.

**Comment by Greg-21** [comment]
What do you mean by "values get reset"? I tested this rule again and both cookie injection and banner clicking work for me on asus.com. Nothing has changed in this regard since the last time we talked.

Here's how the cookie injection works on my end:

https://github.com/mozilla/cookie-banner-rules-list/assets/34160838/835b8392-b620-4a6d-9534-6614c530a502

**Comment by abhishekmadan30** [comment]
Screenshot 2023-12-12 at 4 20 45 PM

This is what I am seeing. As the cookies are there but have no value set even after the mechanisms has run. @Trikolon  Could you please check this out ?

**Comment by Greg-21** [comment]
May I ask you to reopen this pull request? It can always be closed again later if it turns out that nothing will come out of it.

**Comment by Greg-21** [comment]
May I ask you to reopen this pull request for better visibility? It can always be closed again later if it turns out that nothing will come out of it.

**Comment by Greg-21** [comment]
I'm closing this in favor of PR #493, as the motives are different now and the banner is different too.

**Pull request closed without merging**
