### PR TITLE
Add rule for thenextweb.com

### PR DESCRIPTION
**Pull request by metametapod**
## Example URL

`https://www.thenextweb.com`

## Screenshot

Screenshot 2024-01-14 at 16 08 42

Tested on Firefox 122.0b9

### CODE REVIEW

**Review by abhishekmadan30 — COMMENTED** [review]
There is another banner that appears before the cookie banner that blocks it from being handled and as we currently don't support the handling for 2 different banners, I will leave this PR open

**Review by abhishekmadan30 — COMMENTED** [review]
The cookie injection rule does not seem to work. The click rule does work well. Could you please remove the injection rule and re-submit. Thanks :)

**Comment by metametapod** [comment]
Fixed the cookie injection rule. Let me know if that works (confirmed on my machine)

**Review by abhishekmadan30 — APPROVED** [review]
Nice, Thanks :)

**Pull request merged**
