### PR TITLE
Added OneTrust opt-out rule

### PR DESCRIPTION
**Pull request by palant**
OneTrust banner has an opt-out button, not only opt-in. I only tested a bunch of domains on the list, but where I did opt-out now works.

### CODE REVIEW

**Comment by palant** [comment]
Thank you, understood my mistake now. While all of these domains have an opt-out button that will dismiss the banner, most of the time it is hidden and this action will not be saved. So the next time you load a page, the banner shows up again.

Then it’s only a few domains where this opt-out button really works correctly. Moved those up.

**Comment by Trikolon** [comment]
We've removed the hiding behavior recently so that it doesn't look like we can handle a banner where we actually don't. I recommend to test rules with the latest version of Firefox Nightly.

**Comment by Greg-21** [comment]
Would it be okay for you if I included your changes in my pull request (#335) that I opened a few days ago? By doing so, the maintainers of this project wouldn't have to merge yet another pull request for the same CMP.

**Comment by palant** [comment]
> Would it be okay for you if I included your changes in my pull request (#335) that I opened a few days ago?

From what I can tell, you already did. Ok, duplicate of #335 then.

**Pull request closed without merging**
