### PR TITLE
Added various websites to the non-global OneTrust rules

### LINKED ISSUE #71: cnn.com reloads
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/2

> **Firefox Version:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
> **Window Size (inner width and height):** 1920x947
> **GitHub Username:** @pedroldk
> ## Steps to Reproduce
> Go to https://cnn.com
>
> ## Expected Behavior
> The page should not reload.
>
> ## Actual Behavior
> Went to cnn.com and although the site didn't show the cookie banner as expected, the page reloaded. This behaviour might break redirects or pop-ups on some websit

### LINKED ISSUE #74: Cookie prompt isn't cleared on politico.com
via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/5

> **Firefox Version:** Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
> **Window Size (inner width and height):** 1280x955
> **GitHub Username:** @jnv
> ## Steps to Reproduce
> 1) Visit https://www.politico.com/
>
> ## Expected Behavior
> I shouldn't see a cookie prompt
>
> ## Actual Behavior
> I see "We Care About Your Privacy" pop-over (more than one actually
>
> ## Attachment
> Attachment
> [Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/ac62df79-3d95-4f3b-b3e3-768067198c8c.png)

### LINKED ISSUE #154: Cookie dialogue is shown on lifewire
Via https://github.com/mozilla/Foxfooding_Cookie_Banner_Handling/issues/43

---

**Firefox Version:** Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/109.0 Firefox/109.0
**Window Size (inner width and height):** 414x785
## Steps to Reproduce
Load the page.

## Expected Behavior
Cookie dialogue should be handled with automatically.

## Actual Behavior
Nothing.

## Attachment
Attachment
[Link to the original attachment](https://mk-mozilla-campaign-form.s3.eu-central-1.amazonaws.com/787c3789-2be7-4ead-8cbd-0d25fb4c35f5.png)

### LINKED ISSUE #193: Cookie banner on gq-magazine.co.uk
Example page: https://www.gq-magazine.co.uk/fashion/gallery/best-wayfarers

image

### LINKED ISSUE #334: Cookie banners on trello.com and mediaexpert.pl are no longer handled automatically
It seems that at some point, trello.com and mediaexpert.pl switched to the standard OneTrust cookie banner. As a result, the rules created specifically for them not only fail to do their job but even block the OneTrust global rule, causing the cookie banners to continue to display.

New cookie banner on trello.com:
Cookie-banner-on-trello-com

New cookie banner on mediaexpert.pl:
Cookie-banner-on-mediaexpert-pl

### PR DESCRIPTION
**Pull request by Greg-21**
I suppose that at some point, the non-global OneTrust rules will have to go, but until then, I might as well take advantage of them and add a bunch of websites I came across while browsing the Internet.

Fixes #334
Resolves #154, resolves #193

Closes #71, closes #74

### CODE REVIEW

**Comment by abhishekmadan30** [comment]
Would it possible for you to resubmit the patch without reordering the existing rules

**Comment by Greg-21** [comment]
Here is an alternative commit with the current domain order preserved: [link](https://github.com/mozilla/cookie-banner-rules-list/compare/main...Greg-21:cookie-banner-rules-list-fork:non-global-onetrust-rules-unordered)

Is that format better? If so, I can always modify the commit in this pull request as well.

**Comment by Greg-21** [comment]
Here's an alternative commit with the current domain order preserved: [link](https://github.com/mozilla/cookie-banner-rules-list/compare/main...Greg-21:cookie-banner-rules-list-fork:non-global-onetrust-rules-unordered)

Is that format better? If so, I can always modify the commit in this pull request as well.

**Comment by abhishekmadan30** [comment]
Could you please reformat the commit like the linked commit you had provided

**Comment by Greg-21** [comment]
Yes, I will do that.

**Review by abhishekmadan30 — APPROVED** [review]
Nice, Thanks :)

**Pull request merged**
